export const LOG_TYPES = {
  NETWORK_LOGS: 'NETWORK_LOGS',
  DEVICE_LOGS: 'DEVICE_LOGS',
  CONSOLE_LOGS: 'CONSOLE_LOGS',
  APPLICATION_LOGS: 'APPLICATION_LOGS',
  STEP: 'STEP',
  FAILURE: 'FAILURE',
  HTTP: 'HTTP',
  TEST_LOG: 'TEST_LOG',
  TEST_SCREENSHOT: 'TEST_SCREENSHOT',
  TEXT_LOGS: 'TEXT_LOGS'
};

export const LOG_LEVELS = {
  ERROR: 'ERROR',
  INFO: 'INFO',
  WARNING: 'WARNING',
  WARN: 'WARN',
  SEVERE: 'SEVERE',
  DEBUG: 'DEBUG',
  TRACE: 'TRACE',
  FATAL: 'FATAL'
};

export const TEST_DETAILS_TABS = {
  logs: 'Logs',
  info: 'Info'
};
