import {
  AmazonIcon,
  AndroidIcon,
  AppleIcon,
  ChromeIcon,
  DeviceIcon,
  EdgeIcon,
  FirefoxIcon,
  GoogleIcon,
  HTCIcon,
  HuaweiIcon,
  IEIcon,
  IOSIcon,
  LgIcon,
  MacOSIcon,
  MotorolaIcon,
  NokiaIcon,
  OneplusIcon,
  OperaIcon,
  OppoIcon,
  OSXIcon,
  RealmeIcon,
  SafariIcon,
  SamsungIcon,
  SonyIcon,
  VivoIcon,
  WindowsIcon,
  WindowsPhoneIcon,
  XiaomiIcon,
  YandexIcon
} from 'assets/icons/components';

export const ICON_LIST = {
  'icon-chrome': ChromeIcon,
  'icon-edge': EdgeIcon,
  'icon-firefox': FirefoxIcon,
  'icon-ie': IEIcon,
  'icon-opera': OperaIcon,
  'icon-safari': SafariIcon,
  'icon-yandex': YandexIcon,
  'icon-android': AndroidIcon,
  'icon-ios': IOSIcon,
  'icon-os-x': OSXIcon,
  'icon-macos': MacOSIcon,
  'icon-windows': WindowsIcon,
  'icon-winphone': WindowsPhoneIcon,
  'icon-amazon': AmazonIcon,
  'icon-apple': AppleIcon,
  'icon-google': GoogleIcon,
  'icon-vivo': VivoIcon,
  'icon-huawei': HuaweiIcon,
  'icon-htc': HTCIcon,
  'icon-lg': LgIcon,
  'icon-motorola': MotorolaIcon,
  'icon-nokia': NokiaIcon,
  'icon-oneplus': OneplusIcon,
  'icon-samsung': SamsungIcon,
  'icon-xiaomi': XiaomiIcon,
  'icon-sony': SonyIcon,
  'icon-oppo': OppoIcon,
  'icon-realme': RealmeIcon,
  device_icon: DeviceIcon
};

export const BROWSERS_ICON_LIST = [
  'icon-chrome',
  'icon-edge',
  'icon-firefox',
  'icon-ie',
  'icon-opera',
  'icon-safari',
  'icon-yandex'
];
