export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_SORT = 'UPDATE_SORT';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_ERROR_FILTER = 'UPDATE_ERROR_FILTER';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SELECT_REQUEST = 'SELECT_REQUEST';
export const SET_CONTAINER_WIDTH = 'SET_CONTAINER_WIDTH';
export const SET_IS_PROCESSING = 'SET_IS_PROCESSING';
export const FETCH_FILE = {
  REQUEST: 'FETCH_FILE_REQUEST',
  SUCCESS: 'FETCH_FILE_SUCCESS',
  FAILURE: 'FETCH_FILE_FAILURE'
};
