const FETCH_CREATE_GRID_DATA_PATH = '/create-grid';
const FETCH_GRIDS_PATH = '/grids';
const GRID = '/grid';
const INIT_PATH = '/init';
const ONBOARDING_DATA_PATH = '/onboarding';
const FETCH_CLUSTERS_PATH = '/clusters';
const ONBOARDING_EVENT_LOGS_DATA_PATH = `${ONBOARDING_DATA_PATH}/event-logs`;
const ONBOARDING_REGION_PATH = `${ONBOARDING_DATA_PATH}/region-update`;
const ONBOARDING_STATUS_PATH = `${ONBOARDING_DATA_PATH}/status-update`;
const SSO_PATH = '/auth/start-sso';
const UPDATE_GRID_SETTINGS_PATH = '/update-settings';

export {
  FETCH_CLUSTERS_PATH,
  FETCH_CREATE_GRID_DATA_PATH,
  FETCH_GRIDS_PATH,
  GRID,
  INIT_PATH,
  ONBOARDING_DATA_PATH,
  ONBOARDING_EVENT_LOGS_DATA_PATH,
  ONBOARDING_REGION_PATH,
  ONBOARDING_STATUS_PATH,
  SSO_PATH,
  UPDATE_GRID_SETTINGS_PATH
};
