import { getBaseURL } from '../utils/getBaseURL';

import {
  FETCH_CLUSTERS_PATH,
  FETCH_CREATE_GRID_DATA_PATH,
  FETCH_GRID_PATH,
  FETCH_GRIDS_PATH,
  INIT_PATH,
  ONBOARDING_DATA_PATH,
  ONBOARDING_EVENT_LOGS_DATA_PATH,
  ONBOARDING_REGION_PATH,
  ONBOARDING_STATUS_PATH,
  SSO_PATH,
  UPDATE_GRID_SETTINGS_PATH
} from './apiPaths';

const BASE_URL = getBaseURL();

const INIT_URL = `${BASE_URL}${INIT_PATH}`;
const FETCH_CREATE_GRID_DATA_URL = `${BASE_URL}${FETCH_CREATE_GRID_DATA_PATH}`;
const FETCH_GRIDS_URL = `${BASE_URL}${FETCH_GRIDS_PATH}`;
const FETCH_GRID_URL = `${BASE_URL}${FETCH_GRID_PATH}`;
const FETCH_CLUSTERS_URL = `${BASE_URL}${FETCH_CLUSTERS_PATH}`;
const ONBOARDING_DATA_URL = `${BASE_URL}${ONBOARDING_DATA_PATH}`;
const ONBOARDING_EVENT_LOGS_DATA_URL = `${BASE_URL}${ONBOARDING_EVENT_LOGS_DATA_PATH}`;
const ONBOARDING_REGION_CHANGE_URL = `${BASE_URL}${ONBOARDING_REGION_PATH}`;
const ONBOARDING_STATUS_URL = `${BASE_URL}${ONBOARDING_STATUS_PATH}`;
const SSO_URL = `${BASE_URL}${SSO_PATH}`;
const UPDATE_GRID_SETTINGS_URL = `${BASE_URL}${UPDATE_GRID_SETTINGS_PATH}`;

export {
  FETCH_CLUSTERS_URL,
  FETCH_CREATE_GRID_DATA_URL,
  FETCH_GRID_URL,
  FETCH_GRIDS_URL,
  INIT_URL,
  ONBOARDING_DATA_URL,
  ONBOARDING_EVENT_LOGS_DATA_URL,
  ONBOARDING_REGION_CHANGE_URL,
  ONBOARDING_STATUS_URL,
  SSO_URL,
  UPDATE_GRID_SETTINGS_URL
};
