import { getBaseURL } from '../utils/getBaseURL';

import {
  CREATE_GRID_EVENT_LOGS_DATA_PATH,
  CREATE_TRIAL_GRID_PATH,
  FETCH_CLUSTER_PATH,
  FETCH_CLUSTERS_PATH,
  FETCH_GRID_PROFILES_DATA_PATH,
  FETCH_GRIDS_PATH,
  GRID,
  INIT_PATH,
  SETUP_EVENT_LOGS_DATA_PATH,
  SETUP_PATH,
  SETUP_REGION_PATH,
  SETUP_STATUS_PATH,
  SSO_PATH,
  UPDATE_METADATA_PATH
} from './apiPaths';

const BASE_URL = getBaseURL();

const CREATE_GRID = `${BASE_URL}${GRID}`;
const CREATE_GRID_EVENT_LOGS_DATA_URL = `${BASE_URL}${CREATE_GRID_EVENT_LOGS_DATA_PATH}`;
const CREATE_TRIAL_GRID_URL = `${BASE_URL}${CREATE_TRIAL_GRID_PATH}`;

const INIT_URL = `${BASE_URL}${INIT_PATH}`;
const FETCH_GRID_PROFILES_DATA_URL = `${BASE_URL}${FETCH_GRID_PROFILES_DATA_PATH}`;
const FETCH_GRIDS_URL = `${BASE_URL}${FETCH_GRIDS_PATH}`;

const FETCH_CLUSTER_URL = `${BASE_URL}${FETCH_CLUSTER_PATH}`;
const FETCH_GRID_URL = `${BASE_URL}${GRID}`;
const FETCH_CLUSTERS_URL = `${BASE_URL}${FETCH_CLUSTERS_PATH}`;
const SETUP_DATA_URL = `${BASE_URL}${SETUP_PATH}`;
const SETUP_EVENT_LOGS_DATA_URL = `${BASE_URL}${SETUP_EVENT_LOGS_DATA_PATH}`;
const SETUP_REGION_CHANGE_URL = `${BASE_URL}${SETUP_REGION_PATH}`;
const SETUP_STATUS_URL = `${BASE_URL}${SETUP_STATUS_PATH}`;
const SSO_URL = `${BASE_URL}${SSO_PATH}`;
const UPDATE_GRID_SETTINGS_URL = `${BASE_URL}${GRID}`;
const UPDATE_METADATA_URL = `${BASE_URL}${UPDATE_METADATA_PATH}`;

export {
  CREATE_GRID,
  CREATE_GRID_EVENT_LOGS_DATA_URL,
  CREATE_TRIAL_GRID_URL,
  FETCH_CLUSTER_URL,
  FETCH_CLUSTERS_URL,
  FETCH_GRID_PROFILES_DATA_URL,
  FETCH_GRID_URL,
  FETCH_GRIDS_URL,
  INIT_URL,
  SETUP_DATA_URL,
  SETUP_EVENT_LOGS_DATA_URL,
  SETUP_REGION_CHANGE_URL,
  SETUP_STATUS_URL,
  SSO_URL,
  UPDATE_GRID_SETTINGS_URL,
  UPDATE_METADATA_URL
};
