export const GRAPH_EVENT_MAP = {
  CPUUSAGEPERCENTAGE_EVENT: 'CPU_REALTIME_GRAPH',
  MEMORYMB_EVENT: 'MEMORY_REALTIME_GRAPH',
  NETWORKREADKB_EVENT: 'NETWROK_UPLOAD_GRAPH',
  NETWORKWRITEKB_EVENT: 'NETWORK_DOWNLOAD_GRAPH',
  FPS_EVENT: 'FPS_GRAPH',
  JANKYFPS_EVENT: 'SLOW_FRAMES_GRAPH',
  DISKREADKB_EVENT: 'DISK_READ_GRAPH',
  DISKWRITEKB_EVENT: 'DISK_WRITE_GRAPH',
  BATTERYMAH_EVENT: 'BATTERY_REALTIME_GRAPH'
};

export const otherEvents = {
  BATTERYMAH_EVENT: 'a_GRAPH',
  CPUTHREADS_EVENT: 'q_GRAPH',
  BATTERYPERCENTAGE_EVENT: 'w_GRAPH'
};

export const formatCurrentRealtimeValue = (seriesData, threshold) =>
  `${seriesData[seriesData.length - 1][1]} ${threshold?.unit || ''}`;
