export const GRAPH_EVENT_MAP = {
  CPUUSAGEPERCENTAGE_EVENT: 'CPU_REALTIME_GRAPH',
  MEMORYMB_EVENT: 'MEMORY_REALTIME_GRAPH'
};

export const otherEvents = {
  BATTERYMAH_EVENT: 'a_GRAPH',
  NETWORKREADKB_EVENT: 'b_GRAPH',
  NETWORKWRITEKB_EVENT: 'c_GRAPH',
  FPS_EVENT: 'f_GRAPH',
  JANKYFPS_EVENT: 'g_GRAPH',
  CPUTHREADS_EVENT: 'q_GRAPH',
  BATTERYPERCENTAGE_EVENT: 'w_GRAPH',

  DISKREADKB_EVENT: 'z_GRAPH',
  DISKWRITEKB_EVENT: 'x_GRAPH'
};
