import {
  ArrowDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowUpIcon,
  Bars3Icon,
  BarsArrowUpIcon,
  CalendarIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CursorArrowRaysIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  FolderIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  MagnifyingGlassIcon,
  PaperClipIcon,
  PhotoIcon,
  PlusIcon,
  UsersIcon,
  XCircleIcon,
  XMarkIcon
} from '@heroicons/react/20/solid';
import AttachFileIcon from '@mui/icons-material/AttachFile';
import FolderIconMiui from '@mui/icons-material/Folder';
import InsertPhotoOutlinedIcon from '@mui/icons-material/InsertPhotoOutlined';
import PhotoIconMiui from '@mui/icons-material/Photo';

export {
  ArrowDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowUpIcon,
  AttachFileIcon,
  Bars3Icon,
  BarsArrowUpIcon,
  CalendarIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CursorArrowRaysIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  FolderIcon,
  FolderIconMiui,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  InsertPhotoOutlinedIcon,
  MagnifyingGlassIcon,
  PaperClipIcon,
  PhotoIcon,
  PhotoIconMiui,
  PlusIcon,
  UsersIcon,
  XCircleIcon,
  XMarkIcon
};
