import { FaApple } from 'react-icons/fa';
import { SiJira, SiJirasoftware } from 'react-icons/si';
import {
  ArrowDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowUpIcon,
  Bars3Icon,
  BarsArrowUpIcon,
  BuildingOfficeIcon,
  CalendarIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CreditCardIcon,
  CursorArrowRaysIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  FolderIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  MagnifyingGlassIcon,
  PaperClipIcon,
  PhotoIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  UserIcon,
  UsersIcon,
  XCircleIcon,
  XMarkIcon
} from '@heroicons/react/20/solid';

import AutomationFolderIcon from './CustomIcons/AutomationFolderIcon';
import AutomationIcon from './CustomIcons/AutomationIcon';

export * from 'react-icons/md';

export {
  ArrowDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowUpIcon,
  AutomationFolderIcon,
  AutomationIcon,
  Bars3Icon,
  BarsArrowUpIcon,
  BuildingOfficeIcon,
  CalendarIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CreditCardIcon,
  CursorArrowRaysIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  FaApple,
  FolderIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  MagnifyingGlassIcon,
  PaperClipIcon,
  PhotoIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  SiJira,
  SiJirasoftware,
  UserIcon,
  UsersIcon,
  XCircleIcon,
  XMarkIcon
};
